name: 'python ftp deploy'
description: 'A GitHub Action to upload files to an FTP server'
author: 'Akila Indunil'
inputs:
  host:
    description: 'FTP server hostname'
    required: true
  username:
    description: 'FTP server username'
    required: true
  password:
    description: 'FTP server password'
    required: true
  ftpdir:
    description: 'FTP server directory (default: ./)'
    required: false
    default: './'
  localdir:
    description: 'Local directory to upload (default: ./)'
    required: false
    default: './'
  hashfile:
    description: 'Name of the hash file (default: .file_hashes.json)'
    required: false
    default: '.file_hashes.json'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Verify repository contents
      shell: bash
      run: ls -la

    - name: Copy FTP upload script
      shell: bash
      run: |
        if [ -f ftp_upload.py ]; then
          cp ftp_upload.py $GITHUB_WORKSPACE
          echo "Copied ftp_upload.py to $GITHUB_WORKSPACE"
        else
          echo "ftp_upload.py not found in the repository"
          exit 1
        fi

    - name: Run FTP Upload Script
      shell: bash
      run: python $GITHUB_WORKSPACE/ftp_upload.py
      env:
        FTP_HOST: ${{ inputs.host }}
        FTP_USERNAME: ${{ inputs.username }}
        FTP_PASSWORD: ${{ inputs.password }}
        FTP_DIR: ${{ inputs.ftpdir }}
        LOCAL_DIR: ${{ inputs.localdir }}
        HASH_FILE: ${{ inputs.hashfile }}

branding:
  icon: 'upload'
  color: 'blue'
